/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package werkroosternwgui;

import werkroosternw.*;
import java.awt.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.*;
import java.time.*;
import java.util.ArrayList;
import javax.swing.table.*;

/**
 * WerkroosterNWgui beheert het zichtbare deel van het programma.
 *
 * @author Jonathan van der Steege (2020)
 */
public class WerkroosterNWgui extends javax.swing.JFrame {

    private final WerkroosterNW werkrooster = new WerkroosterNW();
    private MaandKalender kalender;
    private BestandStream bestandStream;
    private ArrayList<Dienst> dienstenWeek;
    private ArrayList<Dienst> dienstenWeekend;
    private ArrayList<LocalDate> kal;
    private ArrayList<Dienst> dienstenMaand;
    private ArrayList<JComboBox> comboArray;
    private final GridLayout dagenLayout = new GridLayout(31, 2, 10, 10);
    private final JPanel lMaandPanel = new JPanel();
    private final JPanel rMaandPanel = new JPanel();
    private final JPanel maandPanel = new JPanel();
    private final JTextArea maandTekstGebied = new JTextArea();
    private final JScrollPane scrollPane = new JScrollPane();
    private final JScrollPane weekTabelScrollPane = new JScrollPane();
    private final JScrollPane weekendTabelScrollPane = new JScrollPane();
    private JTable weekTabel;
    private JTable weekendTabel;
    private DefaultTableModel weekModel = new DefaultTableModel();
    private DefaultTableModel weekendModel = new DefaultTableModel();

    /**
     * Creates new form WerkroosterNWGUI
     */
    public WerkroosterNWgui() {
        initComponents();
        mijnInit();
    }

    /**
     * Initialiseer diensten, vult de combobox met maanden, zet het tekstgebied
     * op onbewerkbaar en deactiveer de 'Bewaar gegevens'-knop.
     */
    private void mijnInit() {
        bestandStream = new BestandStream();
        werkrooster.vulDiensten(bestandStream.inladenWeek(), bestandStream.inladenWeekend());
        scrollPane.setViewportView(maandTekstGebied);
        dienstenWeek = werkrooster.geefDienstenWeek();
        dienstenWeekend = werkrooster.geefDienstenWeekend();
        vulMaandComboBox();
        vulJaarComboBox();
        maandTekstGebied.setEditable(false);
        maandTekstGebied.setFont(new Font("Monospaced", Font.PLAIN, 12));
        toonDienstenButton.setEnabled(false);
        bewaarGegevensKnop.setEnabled(false);
        String tekstGebied = "[Week]\n" + werkrooster.printDienstenWeek() + "\n\n[Weekend]\n" + werkrooster.printDienstenWeekend();
        maandTekstGebied.setText(tekstGebied);
        uitvoerPanel.add(scrollPane);
        comboArray = new ArrayList<>();
        resetTabellen();
        weekTabelPanel.add(weekTabelScrollPane);
        weekendTabelPanel.add(weekendTabelScrollPane);
        pasDataToeKnop.setEnabled(false);
        bewaarDataKnop.setEnabled(false);
        leesData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overFrame = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();
        overWerkroosterNWLabel = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        resetButton = new javax.swing.JButton();
        titelLabel = new javax.swing.JLabel();
        overButton = new javax.swing.JButton();
        hoofdPanel = new javax.swing.JTabbedPane();
        maandTabPanel = new javax.swing.JPanel();
        maandKnoppenPanel = new javax.swing.JPanel();
        maandComboBox = new javax.swing.JComboBox<>();
        vulMaandButton = new javax.swing.JButton();
        toonDienstenButton = new javax.swing.JButton();
        jaarComboBox = new javax.swing.JComboBox<>();
        dagenPanel = new javax.swing.JPanel();
        dienstenTabPanel = new javax.swing.JPanel();
        uitvoerPanel = new javax.swing.JPanel();
        dienstKnoppenPanel = new javax.swing.JPanel();
        bewaarGegevensKnop = new javax.swing.JButton();
        bewerkenTabPanel = new javax.swing.JPanel();
        dataOpslaanPanel = new javax.swing.JPanel();
        leesDataKnop = new javax.swing.JButton();
        pasDataToeKnop = new javax.swing.JButton();
        bewaarDataKnop = new javax.swing.JButton();
        bewerkDienstenPanel = new javax.swing.JPanel();
        weekTabelPanel = new javax.swing.JPanel();
        weekKnoppenPanel = new javax.swing.JPanel();
        voegToeWeekKnop = new javax.swing.JButton();
        verwijderRijWeekKnop = new javax.swing.JButton();
        weekendTabelPanel = new javax.swing.JPanel();
        weekendKnoppenPanel = new javax.swing.JPanel();
        voegToeWeekendKnop = new javax.swing.JButton();
        verwijderRijWeekendKnop = new javax.swing.JButton();
        statusTekstVeld = new javax.swing.JTextField();

        overFrame.setTitle("Over WerkroosterNW");
        overFrame.setMinimumSize(new java.awt.Dimension(500, 500));
        overFrame.setSize(new java.awt.Dimension(590, 575));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(526, 477));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(526, 477));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("WerkroosterNW is gemaakt door Jonathan van der Steege in het voorjaar van \n2020 voor Dinesh Chan.\n\nMet dit programma kun je aan de hand van maand en jaar het werkrooster \ninvullen van de diensten die bij Nieuw Woelwijck gebruikt worden.\n\n\nLicentie-informatie:\n\nThis program is free software: you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation, either version 3 of the License, or\n(at your option) any later version.\n\nThis program is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this program.  If not, see <https://www.gnu.org/licenses/>.");
        jScrollPane1.setViewportView(jTextArea1);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        overWerkroosterNWLabel.setText("WerkroosterNW");
        overWerkroosterNWLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout overFrameLayout = new javax.swing.GroupLayout(overFrame.getContentPane());
        overFrame.getContentPane().setLayout(overFrameLayout);
        overFrameLayout.setHorizontalGroup(
            overFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overFrameLayout.createSequentialGroup()
                        .addComponent(overWerkroosterNWLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overFrameLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap())
        );
        overFrameLayout.setVerticalGroup(
            overFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(overWerkroosterNWLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Werkrooster Nieuw Woelwijck");
        setSize(new java.awt.Dimension(0, 0));

        topPanel.setName(""); // NOI18N
        topPanel.setPreferredSize(new java.awt.Dimension(4, 4));

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        titelLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titelLabel.setText("Werkrooster voor diensten van Nieuw Woelwijck");

        overButton.setText("Over WerkroosterNW");
        overButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addGap(18, 18, 18)
                .addComponent(overButton)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(titelLabel)
                    .addComponent(overButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        maandTabPanel.setLayout(new java.awt.BorderLayout());

        maandKnoppenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Acties"));

        maandComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        maandComboBox.setName(""); // NOI18N

        vulMaandButton.setLabel("Vul maand");
        vulMaandButton.setName(""); // NOI18N
        vulMaandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vulMaandButtonActionPerformed(evt);
            }
        });

        toonDienstenButton.setText("Toon diensten");
        toonDienstenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toonDienstenButtonActionPerformed(evt);
            }
        });

        jaarComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout maandKnoppenPanelLayout = new javax.swing.GroupLayout(maandKnoppenPanel);
        maandKnoppenPanel.setLayout(maandKnoppenPanelLayout);
        maandKnoppenPanelLayout.setHorizontalGroup(
            maandKnoppenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maandKnoppenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jaarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vulMaandButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(toonDienstenButton)
                .addContainerGap())
        );
        maandKnoppenPanelLayout.setVerticalGroup(
            maandKnoppenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maandKnoppenPanelLayout.createSequentialGroup()
                .addGroup(maandKnoppenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jaarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vulMaandButton)
                    .addComponent(toonDienstenButton))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        maandTabPanel.add(maandKnoppenPanel, java.awt.BorderLayout.PAGE_START);

        dagenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Maand"));
        dagenPanel.setPreferredSize(new java.awt.Dimension(4, 4));
        dagenPanel.setLayout(new java.awt.BorderLayout(15, 15));
        maandTabPanel.add(dagenPanel, java.awt.BorderLayout.CENTER);

        hoofdPanel.addTab("Maandoverzicht", maandTabPanel);

        dienstenTabPanel.setLayout(new java.awt.BorderLayout());

        uitvoerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Diensten"));
        uitvoerPanel.setPreferredSize(new java.awt.Dimension(4, 4));
        uitvoerPanel.setLayout(new java.awt.BorderLayout());
        dienstenTabPanel.add(uitvoerPanel, java.awt.BorderLayout.CENTER);
        uitvoerPanel.getAccessibleContext().setAccessibleParent(dienstenTabPanel);

        dienstKnoppenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Acties"));
        dienstKnoppenPanel.setPreferredSize(new java.awt.Dimension(771, 69));

        bewaarGegevensKnop.setText("Bewaar gegevens");
        bewaarGegevensKnop.setAlignmentX(0.5F);
        bewaarGegevensKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bewaarGegevensKnopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dienstKnoppenPanelLayout = new javax.swing.GroupLayout(dienstKnoppenPanel);
        dienstKnoppenPanel.setLayout(dienstKnoppenPanelLayout);
        dienstKnoppenPanelLayout.setHorizontalGroup(
            dienstKnoppenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dienstKnoppenPanelLayout.createSequentialGroup()
                .addContainerGap(608, Short.MAX_VALUE)
                .addComponent(bewaarGegevensKnop)
                .addContainerGap())
        );
        dienstKnoppenPanelLayout.setVerticalGroup(
            dienstKnoppenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dienstKnoppenPanelLayout.createSequentialGroup()
                .addComponent(bewaarGegevensKnop)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        dienstenTabPanel.add(dienstKnoppenPanel, java.awt.BorderLayout.PAGE_START);

        hoofdPanel.addTab("Diensten", dienstenTabPanel);

        bewerkenTabPanel.setLayout(new java.awt.BorderLayout());

        dataOpslaanPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        dataOpslaanPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        leesDataKnop.setText("Lees data in");
        leesDataKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leesDataKnopActionPerformed(evt);
            }
        });
        dataOpslaanPanel.add(leesDataKnop);

        pasDataToeKnop.setText("Pas data toe");
        pasDataToeKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasDataToeKnopActionPerformed(evt);
            }
        });
        dataOpslaanPanel.add(pasDataToeKnop);

        bewaarDataKnop.setText("Bewaar data");
        bewaarDataKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bewaarDataKnopActionPerformed(evt);
            }
        });
        dataOpslaanPanel.add(bewaarDataKnop);

        bewerkenTabPanel.add(dataOpslaanPanel, java.awt.BorderLayout.PAGE_START);

        bewerkDienstenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bewerk diensten"));
        bewerkDienstenPanel.setLayout(new java.awt.GridLayout(2, 1));

        weekTabelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Week"));
        weekTabelPanel.setLayout(new java.awt.BorderLayout());

        weekKnoppenPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        voegToeWeekKnop.setText("Voeg rij toe");
        voegToeWeekKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voegToeWeekKnopActionPerformed(evt);
            }
        });
        weekKnoppenPanel.add(voegToeWeekKnop);

        verwijderRijWeekKnop.setText("Verwijder geselecteerde rij");
        verwijderRijWeekKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verwijderRijWeekKnopActionPerformed(evt);
            }
        });
        weekKnoppenPanel.add(verwijderRijWeekKnop);

        weekTabelPanel.add(weekKnoppenPanel, java.awt.BorderLayout.PAGE_START);

        bewerkDienstenPanel.add(weekTabelPanel);

        weekendTabelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Weekend"));
        weekendTabelPanel.setLayout(new java.awt.BorderLayout());

        weekendKnoppenPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        voegToeWeekendKnop.setText("Voeg rij toe");
        voegToeWeekendKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voegToeWeekendKnopActionPerformed(evt);
            }
        });
        weekendKnoppenPanel.add(voegToeWeekendKnop);

        verwijderRijWeekendKnop.setText("Verwijder geselecteerde rij");
        verwijderRijWeekendKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verwijderRijWeekendKnopActionPerformed(evt);
            }
        });
        weekendKnoppenPanel.add(verwijderRijWeekendKnop);

        weekendTabelPanel.add(weekendKnoppenPanel, java.awt.BorderLayout.PAGE_START);

        bewerkDienstenPanel.add(weekendTabelPanel);

        bewerkenTabPanel.add(bewerkDienstenPanel, java.awt.BorderLayout.CENTER);

        hoofdPanel.addTab("Bewerken", bewerkenTabPanel);

        statusTekstVeld.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addComponent(hoofdPanel)
                    .addComponent(statusTekstVeld))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hoofdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusTekstVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vulMaandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vulMaandButtonActionPerformed
        if (toonMaand()) {
            statusTekstVeld.setText("Maand is gevuld");
        }
        bewaarGegevensKnop.setEnabled(false);
    }//GEN-LAST:event_vulMaandButtonActionPerformed

    private void toonDienstenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toonDienstenButtonActionPerformed
        geefOutput();
        hoofdPanel.setSelectedIndex(1);
        bewaarGegevensKnop.setEnabled(true);
    }//GEN-LAST:event_toonDienstenButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        bestandStream = new BestandStream();
        werkrooster.vulDiensten(bestandStream.inladenWeek(), bestandStream.inladenWeekend());
        dagenPanel.removeAll();
        dagenPanel.updateUI();
        maandComboBox.setSelectedIndex(-1);
        jaarComboBox.setSelectedIndex(0);
        toonDienstenButton.setEnabled(false);
        bewaarGegevensKnop.setEnabled(false);
        String tekstGebied = "[Week]\n" + werkrooster.printDienstenWeek() + "\n\n[Weekend]\n" + werkrooster.printDienstenWeekend();
        maandTekstGebied.setText(tekstGebied);
        comboArray.clear();
        resetTabellen();
        pasDataToeKnop.setEnabled(false);
        bewaarDataKnop.setEnabled(false);
        leesData();
        statusTekstVeld.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * Neemt de naam van de maand en het jaar en voegt dit toe aan de uitvoer.
     * Daarna wordt het weggeschreven naar een bestand.
     *
     * @param evt
     */
    private void bewaarGegevensKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bewaarGegevensKnopActionPerformed
        String maandEnJaar = kalender.geefMaandJaar();
        String uitvoer = maandTekstGebied.getText();
        String bestandsnaam = "werkrooster-" + maandEnJaar + ".txt";
        try {
            schrijfBestand(bestandsnaam, uitvoer);
        } catch (IOException e) {

        }
        statusTekstVeld.setText("Gegevens opgeslagen in '" + bestandsnaam + "'");
    }//GEN-LAST:event_bewaarGegevensKnopActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        overFrame.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void overButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overButtonActionPerformed
        overFrame.setVisible(true);
    }//GEN-LAST:event_overButtonActionPerformed

    /**
     * Haalt de gegevens van de diensten in de week en het weekend op en slaat
     * het op naar bestanden.
     *
     * @param evt
     */
    private void bewaarDataKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bewaarDataKnopActionPerformed
        String dataWeek, dataWeekend;
        dataWeek = werkrooster.dataOpslaanDienstenWeek();
        dataWeekend = werkrooster.dataOpslaanDienstenWeekend();
        try {
            bestandStream.saveData(dataWeek, dataWeekend);
        } catch (IOException e) {

        }
        statusTekstVeld.setText("Data opgeslagen");
    }//GEN-LAST:event_bewaarDataKnopActionPerformed

    private void leesDataKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leesDataKnopActionPerformed
        leesData();
        statusTekstVeld.setText("Data ingelezen");
    }//GEN-LAST:event_leesDataKnopActionPerformed

    private void verwijderRijWeekKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verwijderRijWeekKnopActionPerformed
        int geselecteerdeRij = weekTabel.getSelectedRow();
        if (geselecteerdeRij >= 0) {
            ((DefaultTableModel) weekTabel.getModel()).removeRow(geselecteerdeRij);
        }
    }//GEN-LAST:event_verwijderRijWeekKnopActionPerformed

    private void verwijderRijWeekendKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verwijderRijWeekendKnopActionPerformed
        int geselecteerdeRij = weekendTabel.getSelectedRow();
        if (geselecteerdeRij >= 0) {
            ((DefaultTableModel) weekendTabel.getModel()).removeRow(geselecteerdeRij);
        }
    }//GEN-LAST:event_verwijderRijWeekendKnopActionPerformed

    private void voegToeWeekKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voegToeWeekKnopActionPerformed
        int geselecteerdeRij = weekTabel.getSelectedRow();
        if (geselecteerdeRij >= 0) {
            weekModel.insertRow(geselecteerdeRij, new Object[]{});
        } else {
            weekModel.addRow(new Object[]{});
        }
    }//GEN-LAST:event_voegToeWeekKnopActionPerformed

    private void voegToeWeekendKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voegToeWeekendKnopActionPerformed
        int geselecteerdeRij = weekendTabel.getSelectedRow();
        if (geselecteerdeRij >= 0) {
            weekendModel.insertRow(geselecteerdeRij, new Object[]{});
        } else {
            weekendModel.addRow(new Object[]{});
        }
    }//GEN-LAST:event_voegToeWeekendKnopActionPerformed

    private void pasDataToeKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasDataToeKnopActionPerformed
        pasDataToe();
        statusTekstVeld.setText("Data toegepast");
    }//GEN-LAST:event_pasDataToeKnopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WerkroosterNWgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WerkroosterNWgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WerkroosterNWgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WerkroosterNWgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WerkroosterNWgui().setVisible(true);
            }
        });
    }

    /**
     * Vul de maandkeuze-combobox met maanden.
     */
    private void vulMaandComboBox() {
        maandComboBox.removeAllItems();
        maandComboBox.addItem("Januari");
        maandComboBox.addItem("Februari");
        maandComboBox.addItem("Maart");
        maandComboBox.addItem("April");
        maandComboBox.addItem("Mei");
        maandComboBox.addItem("Juni");
        maandComboBox.addItem("Juli");
        maandComboBox.addItem("Augustus");
        maandComboBox.addItem("September");
        maandComboBox.addItem("Oktober");
        maandComboBox.addItem("November");
        maandComboBox.addItem("December");
        maandComboBox.setSelectedIndex(-1);
    }

    /**
     * Vul de jaarkeuze-combobox met jaren.
     */
    private void vulJaarComboBox() {
        jaarComboBox.removeAllItems();
        jaarComboBox.addItem("2020");
        jaarComboBox.addItem("2021");
        jaarComboBox.addItem("2022");
        jaarComboBox.addItem("2023");
        jaarComboBox.addItem("2024");
        jaarComboBox.addItem("2025");
        jaarComboBox.addItem("2026");
        jaarComboBox.addItem("2027");
        jaarComboBox.addItem("2028");
        jaarComboBox.addItem("2029");
        jaarComboBox.addItem("2030");
    }

    /**
     * Toont de dagen van de maand in de interface. Per dag wordt een combobox
     * gemaakt om de dienst te kiezen.
     */
    private boolean toonMaand() {
        int maand, jaar;
        boolean gevuld = false;
        comboArray.clear();
        if (maandComboBox.getSelectedIndex() >= 0) {
            toonDienstenButton.setEnabled(true);
            maand = maandComboBox.getSelectedIndex() + 1;
            jaar = Integer.parseInt((String) jaarComboBox.getSelectedItem());
            dagenPanel.removeAll();
            maandPanel.removeAll();
            maandPanel.updateUI();
            dagenPanel.updateUI();
            kalender = new MaandKalender(LocalDate.of(jaar, maand, 1));
            kal = kalender.geefMaand();
            maandPanel.setLayout(new GridLayout(0, 7, 10, 10));
            dagenPanel.add(maandPanel, BorderLayout.PAGE_START);
            JLabel maLabel = new JLabel("Ma", JLabel.CENTER);
            maLabel.setFont(new Font("Dialog", Font.BOLD, 12));
            maLabel.setBackground(Color.WHITE);
            maLabel.setOpaque(true);
            maandPanel.add(maLabel);
            JLabel diLabel = new JLabel("Di", JLabel.CENTER);
            diLabel.setFont(new Font("Dialog", Font.BOLD, 12));
            diLabel.setBackground(Color.WHITE);
            diLabel.setOpaque(true);
            maandPanel.add(diLabel);
            JLabel woLabel = new JLabel("Wo", JLabel.CENTER);
            woLabel.setFont(new Font("Dialog", Font.BOLD, 12));
            woLabel.setBackground(Color.WHITE);
            woLabel.setOpaque(true);
            maandPanel.add(woLabel);
            JLabel doLabel = new JLabel("Do", JLabel.CENTER);
            doLabel.setFont(new Font("Dialog", Font.BOLD, 12));
            doLabel.setBackground(Color.WHITE);
            doLabel.setOpaque(true);
            maandPanel.add(doLabel);
            JLabel vrLabel = new JLabel("Vr", JLabel.CENTER);
            vrLabel.setFont(new Font("Dialog", Font.BOLD, 12));
            vrLabel.setBackground(Color.WHITE);
            vrLabel.setOpaque(true);
            maandPanel.add(vrLabel);
            JLabel zaLabel = new JLabel("Za", JLabel.CENTER);
            zaLabel.setFont(new Font("Dialog", Font.BOLD, 12));
            zaLabel.setBackground(Color.ORANGE);
            zaLabel.setOpaque(true);
            maandPanel.add(zaLabel);
            JLabel zoLabel = new JLabel("Zo", JLabel.CENTER);
            zoLabel.setFont(new Font("Dialog", Font.BOLD, 12));
            zoLabel.setBackground(Color.ORANGE);
            zoLabel.setOpaque(true);
            maandPanel.add(zoLabel);
            int begin = kalender.eersteDagMaand();
            int dag = 1;
            for (int i = 0; i < kal.size() + begin; i++) {
                if (i >= begin) {
                    JPanel dagPanel = new JPanel();
                    dagPanel.setLayout(new BorderLayout());
                    String labelTekst = "" + (dag);
                    JLabel label = new JLabel(labelTekst);
                    dagPanel.add(label, BorderLayout.LINE_START);
                    JComboBox combobox = new JComboBox();
                    combobox.addItem("");
                    if ((kal.get(dag - 1).getDayOfWeek() == DayOfWeek.SUNDAY) || (kal.get(dag - 1).getDayOfWeek() == DayOfWeek.SATURDAY)) {
                        for (Dienst d : dienstenWeekend) {
                            combobox.addItem(d.geefNaam());
                        }
                    } else {
                        for (Dienst d : dienstenWeek) {
                            combobox.addItem(d.geefNaam());
                        }
                    }
                    combobox.setSelectedIndex(-1);
                    dagPanel.add(combobox, BorderLayout.LINE_END);
                    if (kalender.isWeekend(dag - 1)) {
                        dagPanel.setBackground(Color.ORANGE);
                    } else {
                        dagPanel.setBackground(Color.WHITE);
                    }
                    comboArray.add(combobox);
                    maandPanel.add(dagPanel);
                    dag++;
                } else {
                    JPanel dagPanel = new JPanel();
                    dagPanel.add(new JLabel());
                    maandPanel.add(dagPanel);
                }
            }
            gevuld = true;
        }
        return gevuld;
    }

    /**
     * Neemt de keuzes van diensten voor de dagen en geeft alle informatie weer
     * in het tekstgebied
     */
    private void geefOutput() {
        maandTekstGebied.setText("");
        ArrayList<String> namen = new ArrayList<>();
        String tekst = "" + kalender.geefMaandJaar() + "\n\n";
        for (JComboBox c : comboArray) {
            namen.add((String) c.getSelectedItem());
        }
        for (int i = 0; i < namen.size(); i++) {
            if (namen.get(i) != null && !namen.get(i).equals("")) {
                String tekstDienst = "";
                if (kalender.isWeekend(i)) {
                    for (Dienst d : dienstenWeekend) {
                        if (d.geefNaam().equals(namen.get(i))) {
                            tekstDienst = " w dienst " + d.geefTotaal();
                        }
                    }
                } else {
                    for (Dienst d : dienstenWeek) {
                        if (d.geefNaam().equals(namen.get(i))) {
                            tekstDienst = "   dienst " + d.geefTotaal();
                        }
                    }
                }
                if (i < 9) {
                    tekst += " " + (i + 1) + tekstDienst + "\n";
                } else {
                    tekst += (i + 1) + tekstDienst + "\n";
                }
            }
        }
        maandTekstGebied.setText(tekst);
    }

    /**
     * Schrijf de informatie van dagen van de maand met bijbehorend de dienst,
     * werktijden en opmerkingen naar een bestand.
     *
     * @param bestandsnaam Naam van het bestand
     * @param tekst Tekst die moet worden weggeschreven
     * @throws IOException Mocht er een fout optreden, wordt deze afgevangen
     */
    private static void schrijfBestand(String bestandsnaam, String tekst)
            throws IOException {
        File bestand = new File(bestandsnaam);
        try (BufferedWriter out = new BufferedWriter(new FileWriter(bestand))) {
            out.write(tekst);
            out.close();
        }
    }

    /**
     * Herstelt de tabellen (week en weekend) naar de lege stand.
     */
    private void resetTabellen() {
        weekModel = new DefaultTableModel();
        weekendModel = new DefaultTableModel();
        weekModel.addColumn("Naam");
        weekModel.addColumn("Tijd van");
        weekModel.addColumn("Tijd tot");
        weekModel.addColumn("Opmerkingen");
        weekTabel = new JTable(weekModel);
        weekendModel.addColumn("Naam");
        weekendModel.addColumn("Tijd van");
        weekendModel.addColumn("Tijd tot");
        weekendModel.addColumn("Opmerkingen");
        weekendTabel = new JTable(weekendModel);
        weekTabelScrollPane.setViewportView(weekTabel);
        weekendTabelScrollPane.setViewportView(weekendTabel);
    }

    /**
     * Haalt de gegevens van de diensten van de week en het weekend op en
     * plaatst dit in de tabellen.
     */
    private void leesData() {
        resetTabellen();
        for (Dienst d : dienstenWeek) {
            String naam = d.geefNaam().trim();
            String tijdVan = d.geefTijdVan().trim();
            String tijdTot = d.geefTijdTot().trim();
            String opmerkingen = d.geefOpmerkingen().trim();
            weekModel.addRow(new Object[]{naam, tijdVan, tijdTot, opmerkingen});
        }
        for (Dienst d : dienstenWeekend) {
            String naam = d.geefNaam().trim();
            String tijdVan = d.geefTijdVan().trim();
            String tijdTot = d.geefTijdTot().trim();
            String opmerkingen = d.geefOpmerkingen().trim();
            weekendModel.addRow(new Object[]{naam, tijdVan, tijdTot, opmerkingen});
        }
        pasDataToeKnop.setEnabled(true);
        bewaarDataKnop.setEnabled(true);
    }

    /**
     * Haalt de gegevens uit de tabellen op en vult de overzichten van de
     * diensten van de week en het weekend hiermee.
     */
    private void pasDataToe() {
        ArrayList<Dienst> dienstenWeekNieuw = new ArrayList<>();
        ArrayList<Dienst> dienstenWeekendNieuw = new ArrayList<>();
        for (int i = weekTabel.getRowCount() - 1; i >= 0; i--) {
            if (weekTabel.getValueAt(i, 0) == null) {
                ((DefaultTableModel) weekTabel.getModel()).removeRow(i);
            }
        }
        for (int i = 0; i < weekTabel.getRowCount(); i++) {
            String naam, tijdVan, tijdTot, opmerkingen;
            naam = (String) weekTabel.getValueAt(i, 0);
            tijdVan = (String) weekTabel.getValueAt(i, 1);
            if (tijdVan.length() == 4) {
                tijdVan = " " + tijdVan;
            }
            tijdTot = (String) weekTabel.getValueAt(i, 2);
            if (tijdTot.length() == 4) {
                tijdTot = " " + tijdTot;
            }
            opmerkingen = (String) weekTabel.getValueAt(i, 3);
            dienstenWeekNieuw.add(new Dienst(naam, tijdVan, tijdTot, opmerkingen));
        }
        for (int i = weekendTabel.getRowCount() - 1; i >= 0; i--) {
            if (weekendTabel.getValueAt(i, 0) == null) {
                ((DefaultTableModel) weekendTabel.getModel()).removeRow(i);
            }
        }
        for (int i = 0; i < weekendTabel.getRowCount(); i++) {
            String naam, tijdVan, tijdTot, opmerkingen;
            naam = (String) weekendTabel.getValueAt(i, 0);
            tijdVan = (String) weekendTabel.getValueAt(i, 1);
            if (tijdVan.length() == 4) {
                tijdVan = " " + tijdVan;
            }
            tijdTot = (String) weekendTabel.getValueAt(i, 2);
            if (tijdTot.length() == 4) {
                tijdTot = " " + tijdTot;
            }
            opmerkingen = (String) weekendTabel.getValueAt(i, 3);
            dienstenWeekendNieuw.add(new Dienst(naam, tijdVan, tijdTot, opmerkingen));
        }
        werkrooster.vulDiensten(dienstenWeekNieuw, dienstenWeekendNieuw);
        dagenPanel.removeAll();
        dagenPanel.updateUI();
        maandComboBox.setSelectedIndex(-1);
        jaarComboBox.setSelectedIndex(0);
        toonDienstenButton.setEnabled(false);
        bewaarGegevensKnop.setEnabled(false);
        String tekstGebied = "[Week]\n" + werkrooster.printDienstenWeek() + "\n\n[Weekend]\n" + werkrooster.printDienstenWeekend();
        maandTekstGebied.setText(tekstGebied);
        comboArray.clear();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bewaarDataKnop;
    private javax.swing.JButton bewaarGegevensKnop;
    private javax.swing.JPanel bewerkDienstenPanel;
    private javax.swing.JPanel bewerkenTabPanel;
    private javax.swing.JPanel dagenPanel;
    private javax.swing.JPanel dataOpslaanPanel;
    private javax.swing.JPanel dienstKnoppenPanel;
    private javax.swing.JPanel dienstenTabPanel;
    private javax.swing.JTabbedPane hoofdPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jaarComboBox;
    private javax.swing.JButton leesDataKnop;
    private javax.swing.JComboBox<String> maandComboBox;
    private javax.swing.JPanel maandKnoppenPanel;
    private javax.swing.JPanel maandTabPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton overButton;
    private javax.swing.JFrame overFrame;
    private javax.swing.JLabel overWerkroosterNWLabel;
    private javax.swing.JButton pasDataToeKnop;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField statusTekstVeld;
    private javax.swing.JLabel titelLabel;
    private javax.swing.JButton toonDienstenButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel uitvoerPanel;
    private javax.swing.JButton verwijderRijWeekKnop;
    private javax.swing.JButton verwijderRijWeekendKnop;
    private javax.swing.JButton voegToeWeekKnop;
    private javax.swing.JButton voegToeWeekendKnop;
    private javax.swing.JButton vulMaandButton;
    private javax.swing.JPanel weekKnoppenPanel;
    private javax.swing.JPanel weekTabelPanel;
    private javax.swing.JPanel weekendKnoppenPanel;
    private javax.swing.JPanel weekendTabelPanel;
    // End of variables declaration//GEN-END:variables
}
